sudo: required
services:
  - docker

before_install:
  - docker build -t fireballvelvet/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true fireballvelvet/react-test npm test

after_success:
  - docker build -t fireballvelvet/multi-client ./client
  - docker build -t fireballvelvet/multi-nginx ./nginx
  - docker build -t fireballvelvet/multi-server ./server
  - docker build -t fireballvelvet/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin 
  - docker push fireballvelvet/multi-client
  - docker push fireballvelvet/multi-nginx
  - docker push fireballvelvet/multi-server
  - docker push fireballvelvet/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'ap-southeast-2'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-ap-southeast-2-871839928032'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: $AWS_SECRET_KEY
